In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv('Electric_Production.csv')

In [8]:
df.isnull().sum()

DATE          0
IPG2211A2N    0
dtype: int64

In [9]:
df

          DATE  IPG2211A2N
0     1/1/1985     72.5052
1     2/1/1985     70.6720
2     3/1/1985     62.4502
3     4/1/1985     57.4714
4     5/1/1985     55.3151
..         ...         ...
392   9/1/2017     98.6154
393  10/1/2017     93.6137
394  11/1/2017     97.3359
395  12/1/2017    114.7212
396   1/1/2018    129.4048

[397 rows x 2 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   DATE        397 non-null    object
 1   IPG2211A2N  397 non-null    float64
dtypes: float64(1), object(1)
memory usage: 6.3+ KB

In [12]:
df.describe()

       IPG2211A2N
count  397.000000
mean    88.847218
std     15.387834
min     55.315100
25%     77.105200
50%     89.779500
75%    100.524400
max    129.404800

In [13]:
df.columns

Index(['DATE', 'IPG2211A2N'], dtype='object')

In [14]:
df_sampoo=pd.read_csv('sales-of-shampoo-over-a-three-ye.csv')

In [15]:
df_sampoo

    Month  Sales of shampoo over a three year period
0   1-Jan                                      266.0
1   1-Feb                                      145.9
2   1-Mar                                      183.1
3   1-Apr                                      119.3
4   1-May                                      180.3
5   1-Jun                                      168.5
6   1-Jul                                      231.8
7   1-Aug                                      224.5
8   1-Sep                                      192.8
9   1-Oct                                      122.9
10  1-Nov                                      336.5
11  1-Dec                                      185.9
12  2-Jan                                      194.3
13  2-Feb                                      149.5
14  2-Mar                                      210.1
15  2-Apr                                      273.3
16  2-May                                      191.4
17  2-Jun                                      287.0
18  2-Jul                                      226.0
19  2-Aug                                      303.6
20  2-Sep                                      289.9
21  2-Oct                                      421.6
22  2-Nov                                      264.5
23  2-Dec                                      342.3
24  3-Jan                                      339.7
25  3-Feb                                      440.4
26  3-Mar                                      315.9
27  3-Apr                                      439.3
28  3-May                                      401.3
29  3-Jun                                      437.4
30  3-Jul                                      575.5
31  3-Aug                                      407.6
32  3-Sep                                      682.0
33  3-Oct                                      475.3
34  3-Nov                                      581.3
35  3-Dec                                      646.9

In [16]:
df.head()

       DATE  IPG2211A2N
0  1/1/1985     72.5052
1  2/1/1985     70.6720
2  3/1/1985     62.4502
3  4/1/1985     57.4714
4  5/1/1985     55.3151